apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-app-config
  namespace: default
data:
  application.properties: |
    spring.application.name=ping
    server.port=9800
    # spring.cloud.kubernetes.loadbalancer.mode=service
    spring.config.import=optional:configserver
    spring.cloud.config.enabled=false
    ping.message=Hello K3s!
