apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping
  name: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - image: motomark/ping
        name: ping
        ports: 
        - containerPort: 9800
---
kind: Service
apiVersion: v1
metadata:
  name: ping-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ping
  ports:
  - name: http
    port: 9800
    protocol: TCP
    targetPort: 9800

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ping-entrypoint
#   namespace: default
# spec:
#   type: NodePort
#   selector:
#     app: ping
#   ports:
#     - port: 9800
#       targetPort: 9800
#       nodePort: 30002

